[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[functions]
  external_node_modules = ["express", "cors", "sqlite3", "bcryptjs", "jsonwebtoken", "nodemailer", "zod", "serverless-http"]
  node_bundler = "esbuild"
  included_files = ["data/**/*", "server/**/*", "shared/**/*"]

# API redirects - все /api/* запросы идут к Netlify функции
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Безопасность для API
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Статические ресурсы
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML страницы
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# SPA fallback - все остальные маршруты идут к index.html для клиентского роутинга
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Обработка ошибок
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200
